# This is a basic workflow to help you get started with Actions

name: boa noite bruno

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  boa-noite-bruno:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout top
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Dando boa noite
        run: echo Boa noite Bruno

      # Runs a set of commands using the runners shell
      - name: Até logo
        run: |
          echo Durma bem cara
          echo Até amanhã...
